import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex relative w-full flex-col min-h-screen h-full">
          <Navbar />
          <div className="flex w-full h-full">
            <Sidebar />
            <div className="flex w-full h-full pb-6">{children}</div>
          </div>
          <Modal />
        </main>
      </body>
    </html>
  );
}
